### ISSUE TITLE
esp32 works (after disabling core0 WDT)

### ISSUE THREAD

**Issue by thijses** [rtlopez/esp-fc#10]
i noticed since Alpha0 that it compiles for the ESP32 and seems to work, but crashes after like 5-10 seconds, and when i checked the error backtrace, it was pointing towards the task_wdt_isr, so i added `disableCore0WDT();` and now it just seems to work fine. i assume you are aware of the existance of the Core0 WDT, which will timout after a few second when running a task on core 0, unless it's reset (`esp_task_wdt_reset();` ) (which in many example sketches on the internet is sneakily done with a delay() (or i2s_write_bytes(), btw).
(to be clear: i added disableCore0WDT() as the fist like of otherTask(), but it probably also works from setup());

**Comment by rtlopez** [comment]
@thijses thanks, I'll need to dive into it, but so far I'll follow your suggestion. Cheers.
