### ISSUE TITLE
Betaflight cant connect over WiFi

### ISSUE THREAD

**Issue by Bleach665** [rtlopez/esp-fc#109]
First of all, many thanks to @rtlopez for a great project!

I try to connect Betaflight to esp32 over WiFi, but receive error `Failed to open serial port`.
In serial console all work perfect:
<details>

````
# status 
ESPF ESP32 v0.0.0 0000000 Jan 22 2024 15:11:44 8.4.0 201103
STATUS: 
    cpu freq: 240 MHz
  gyro clock: 8000 Hz
   gyro rate: 2000 Hz
   loop rate: 250 Hz
  mixer rate: 250 Hz
  accel rate: 500 Hz
   baro rate: 83 Hz
    mag rate: 75 Hz

 gyro device: MPU6050/I2C
 baro device: BMP280/I2C
  mag device: HMC5883L/I2C
     rx rate: 43
     rx lpfs: 0.00, 0.14

 arming disabled: 16777222

````
</details>

Also, Betaflight configurator work fine over COM port.

To connect over WiFi I set in COM port console SSID, password, `wifi_mode` to `1`. After `save` and `reboot`. On this step, esp32 present in router clients list. Also, I can ping it. In betaflight configurator I select `Manual selection` on `Welcome` page. In `port` I enter esp32 ip adress: `tcp://192.168.1.36`. And receive described above arror.
Betaflight configurator ver. 10.8 and 10.9 were tried.

**Comment by rtlopez** [comment]
You need to specify port numer with address, by default it is 1111: `tcp://192.168.1.36:1111`
