### ISSUE TITLE
Bdir-dshot 300 error 100%

### ISSUE THREAD

**Issue by sysytwl** [rtlopez/esp-fc#121]
Hi, I'm using dshot300 with Bidir on. But I got 100% error in betaflight and RPM 0 all the time. I've tested it on a stm32f3 and it is working. hence the ESC is working correctly. is this normal?

**Comment by rtlopez** [comment]
what type of esc are you using and what firmware is loaded to it?

**Comment by sysytwl** [comment]
ESP32-S3
latest-esp-fc master, unchanged
G-h-20, 16,9, https://github.com/JazzMaverick/BLHeli/tree/JazzMaverick-patch-1?tab=readme-ov-file

**Comment by rtlopez** [comment]
@sysytwl Why JazzMaverick? this firmware is not maintained for very long time. So far I've tested combination of ESP32 + Bluejay. For S3 I'm in process of completiing hardware ATM So I'll be able to verify in several days.

**Comment by sysytwl** [comment]
ok, thx for the info. I'll check that.

**Comment by sysytwl** [comment]
hi, I tried with Bluejay. It seems to have the same issue.

**Comment by rtlopez** [comment]
@sysytwl in develop branch there are fixes for dshot-bidir, now rpm should be shown on ESP32-S3. If you are able to verify, that would be great.

**Comment by sysytwl** [comment]
![image](https://github.com/rtlopez/esp-fc/assets/61526569/58085267-c359-4b3c-9f3a-1e312a2c012b)
it's working. thx a lot.
