### ISSUE TITLE
how should I connect

### ISSUE THREAD

**Issue by bugjiang82** [rtlopez/esp-fc#132]
Thank you very much for making such an excellent software. I have a question now. I have already flashed ESP32-S3 and can successfully connect to Betaflight. I have a Flysky I6 remote controller and an FS-IA6B receiver. Now how should I connect them? Do I need to use the "get pin" command to obtain the "rx" interface and then connect RX, 5V, and GND to the receiver?

**Comment by rtlopez** [comment]
in ppm mode connect to pin that is assigned to `pin_input_rx` parameter.
