### ISSUE TITLE
flashing problem in esptool!

### ISSUE THREAD

**Issue by Zuhayer69** [rtlopez/esp-fc#133]
I have a esp 32 dev module rev3 which i connected through usb and in esp tool i conected the board but I am am confused what file i should select for the firmware. Please tell me the firmware file name basically which file to choose to flash.

**Comment by rtlopez** [comment]
espfc_v0.2.0-RC6_esp32_0x00.bin.zip, remeber to extract and follow guide https://github.com/rtlopez/esp-fc?tab=readme-ov-file#flashing

**Comment by Zuhayer69** [comment]
> `espfc_v0.2.0-RC6_esp32_0x00.bin.zip`, remeber to extract and follow guide https://github.com/rtlopez/esp-fc?tab=readme-ov-file#flashing
Thanks for the reply I am going to test it as soon as possible and I will let you know

**Comment by rtlopez** [comment]
esp32-c3 and esp32-s3 is not supported by this flasher. At the moment you need to use vscode with platformio extension.

**Comment by Zuhayer69** [comment]
Will the schematics be same for the esp32 s3 module as the esp32 module? Or there is a difference ?

**Comment by rtlopez** [comment]
no, pin assignment is diferrent. If you flash board, then go to the Cli and type `get pin` to see pin functions.

**Comment by Zuhayer69** [comment]
the ADC pin for esp32 is two shown in the CLI one is ADC 0 and another is ADC 1 which one to use? please help

**Comment by bsvdoom** [comment]
> the ADC pin for esp32 is two shown in the CLI one is ADC 0 and another is ADC 1 which one to use? please help

Try ADC 0

**Comment by rtlopez** [comment]
ADC_0 is for voltage, ADC_1 is for current. Do not confuse it with internal `ADC` number of esp chip. Use only pins attached to `ADC1` of esp32.
