### ISSUE TITLE
Firmware File reference

### ISSUE THREAD

**Issue by auroraborealis207** [rtlopez/esp-fc#140]
The Flashing section is denoting a .bin firmware file to upload ,I am unable to find any file related which is of the same format ,I also tried compiling to an image using docker but resulted in a .fzz file which failed to connect to beta flight , I am using the most lastest version of betaflight
![image](https://github.com/user-attachments/assets/dd7d21fb-8a88-4f37-9aff-a5061f82b4de)
![image](https://github.com/user-attachments/assets/0f461518-b938-4b10-91cd-68df969846be)

**Comment by auroraborealis207** [comment]
First Image is Beta Flight and Second from Flasher

**Comment by auroraborealis207** [comment]
using ESP-Wroom-32

**Comment by rtlopez** [comment]
On the releases page https://github.com/rtlopez/esp-fc/releases click **Assets**

**Comment by auroraborealis207** [comment]
Thanks for the clarification!!!
