### ISSUE TITLE
Is CRSF/eLRS supported with ESP32?

### ISSUE THREAD

**Issue by axife** [rtlopez/esp-fc#23]
I found from source code that 1/3, 32/33, 17/16 pins used for serial and I tried all. But I can't get ELRS working. 

I guess 1/3 is not possible to use. (UART1 in BF terminology)
Is 17/16 (UART3 in BF terminology) best suited for connecting ELRS received? 

(I fail to compile for ESP8266)

**Comment by rtlopez** [comment]
Unfortunately CRSF is not implemented yet, only SBUS.

for esp8266 you can try the `pico` branch, currently it is the most recent version, but there is a lot of untested changes.
