### ISSUE TITLE
Is this still a work in progress?? I like to help!

### ISSUE THREAD

**Issue by techboycr** [rtlopez/esp-fc#3]
Hi, there is no issue what so ever. 
I am just amazed by this project, I love quads And I have a not so secert affair with the ESP8266, so let me know how may I help.

I will start rigth away with my build, I have a frame that can use this FC.

**Comment by rtlopez** [comment]
Have a look at the develop branch, mostly I'm working on esp32 port and new peripherals. If you are willing to help, make your board flyable, share your experiences, create/solve issues, collect blackbox logs and have fun ;)
