### ISSUE TITLE
wemos d1 mini can't connect betaflight configurator

### ISSUE THREAD

**Issue by AutoPlantBali** [rtlopez/esp-fc#32]
![error_betaflight](https://github.com/rtlopez/esp-fc/assets/100328812/b636f145-56c7-4072-a361-d5f82a577256)

-> betaflight configurator 10.9.0
-> board esp8266 wemos d1 mini
-> mpu6050

after flash can't connect to betaflight configurator

**Comment by rtlopez** [comment]
Hi @AutoPlantBali 

thanks for your report, can you provide me a firmware version you're using?

Are you able to connect to cli (115200 8N1) with alternative terminal, like PlatformIO, Arduino IDE, Putty, or Miniterm and type `status` command twice or more times?

**Comment by AutoPlantBali** [comment]
thanks for replying..

i'am use visual code + PlatformIO, this result after click upload and monitor:

Processing d1_mini (board: d1_mini; platform: espressif8266; framework: arduino)
--------------------------------------------------------------------------------------------------------------------------------Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif8266/d1_mini.html
PLATFORM: Espressif 8266 (4.0.1) > WeMos D1 R2 and mini
HARDWARE: ESP8266 160MHz, 80KB RAM, 4MB Flash
PACKAGES:
 - framework-arduinoespressif8266 @ 3.30002.0 (3.0.2)
 - tool-esptool @ 1.413.0 (4.13)
 - tool-esptoolpy @ 1.30000.201119 (3.0.0)
 - tool-mklittlefs @ 1.203.210628 (2.3)
 - tool-mkspiffs @ 1.200.0 (2.0)
 - toolchain-xtensa @ 2.100300.220621 (10.3.0)
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 45 compatible libraries
Scanning dependencies...
Dependency Graph
|-- Espfc
|-- betaflight       
|-- EEPROM @ 1.0     
|-- EscDriver        
|-- ESP8266WiFi @ 1.0
|-- EspGpio
|-- EspSoftSerial    
|-- EspWire
|-- Kalman
|-- AHRS
|-- printf
|-- SPI @ 1.0        
|-- Wire @ 1.0       
Building in release mode
Compiling .pio\build\d1_mini\src\main.cpp.o
Generating LD script .pio\build\d1_mini\ld\local.eagle.app.v6.common.ld
Compiling .pio\build\d1_mini\lib69c\printf\printf.c.o
Archiving .pio\build\d1_mini\lib69c\libprintf.a
Compiling .pio\build\d1_mini\libcd2\betaflight\blackbox\blackbox.c.o
Compiling .pio\build\d1_mini\libcd2\betaflight\blackbox\blackbox_encoding.c.o
Compiling .pio\build\d1_mini\libcd2\betaflight\blackbox\blackbox_io.c.o
Compiling .pio\build\d1_mini\libcd2\betaflight\platform.c.o
Archiving .pio\build\d1_mini\libcd2\libbetaflight.a
Compiling .pio\build\d1_mini\lib7f9\EscDriver\EscDriverEsp8266.cpp.o
Compiling .pio\build\d1_mini\lib7f9\EscDriver\EscDriverRP2040.cpp.o
Archiving .pio\build\d1_mini\lib7f9\libEscDriver.a
Compiling .pio\build\d1_mini\libaec\AHRS\Madgwick.cpp.o
Compiling .pio\build\d1_mini\libaec\AHRS\Mahony.cpp.o
Archiving .pio\build\d1_mini\libaec\libAHRS.a
Compiling .pio\build\d1_mini\libf83\EspSoftSerial\EspSoftSerial.cpp.o
Archiving .pio\build\d1_mini\libf83\libEspSoftSerial.a
Compiling .pio\build\d1_mini\libe6b\EspWire\EspWire.cpp.o
Compiling .pio\build\d1_mini\libe6b\EspWire\esp_twi.cpp.o
Archiving .pio\build\d1_mini\libe6b\libEspWire.a
Compiling .pio\build\d1_mini\libe23\Wire\Wire.cpp.o
Compiling .pio\build\d1_mini\libf2d\SPI\SPI.cpp.o
Archiving .pio\build\d1_mini\libe23\libWire.a
Compiling .pio\build\d1_mini\lib586\Kalman\Kalman.cpp.o
Archiving .pio\build\d1_mini\libf2d\libSPI.a
Archiving .pio\build\d1_mini\lib586\libKalman.a
Compiling .pio\build\d1_mini\lib627\EEPROM\EEPROM.cpp.o
Compiling .pio\build\d1_mini\lib4d9\ESP8266WiFi\BearSSLHelpers.cpp.o
Archiving .pio\build\d1_mini\lib627\libEEPROM.a
Compiling .pio\build\d1_mini\lib4d9\ESP8266WiFi\CertStoreBearSSL.cpp.o
Compiling .pio\build\d1_mini\lib4d9\ESP8266WiFi\ESP8266WiFi.cpp.o
Compiling .pio\build\d1_mini\lib4d9\ESP8266WiFi\ESP8266WiFiAP.cpp.o
Compiling .pio\build\d1_mini\lib4d9\ESP8266WiFi\ESP8266WiFiGeneric.cpp.o
Compiling .pio\build\d1_mini\lib4d9\ESP8266WiFi\ESP8266WiFiGratuitous.cpp.o
Compiling .pio\build\d1_mini\lib4d9\ESP8266WiFi\ESP8266WiFiMulti.cpp.o
Compiling .pio\build\d1_mini\lib4d9\ESP8266WiFi\ESP8266WiFiSTA-WPS.cpp.o
Compiling .pio\build\d1_mini\lib4d9\ESP8266WiFi\ESP8266WiFiSTA.cpp.o
Compiling .pio\build\d1_mini\lib4d9\ESP8266WiFi\ESP8266WiFiScan.cpp.o
Compiling .pio\build\d1_mini\lib4d9\ESP8266WiFi\WiFiClient.cpp.o
Compiling .pio\build\d1_mini\lib4d9\ESP8266WiFi\WiFiClientSecureBearSSL.cpp.o
Compiling .pio\build\d1_mini\lib4d9\ESP8266WiFi\WiFiServer.cpp.o
Compiling .pio\build\d1_mini\lib4d9\ESP8266WiFi\WiFiServerSecureBearSSL.cpp.o
Compiling .pio\build\d1_mini\lib4d9\ESP8266WiFi\WiFiUdp.cpp.o
Compiling .pio\build\d1_mini\lib4d9\ESP8266WiFi\enable_wifi_at_boot_time.cpp.o
Compiling .pio\build\d1_mini\libf7d\Espfc\Device\InputPPM.cpp.o
Archiving .pio\build\d1_mini\lib4d9\libESP8266WiFi.a
Archiving .pio\build\d1_mini\libFrameworkArduinoVariant.a
Archiving .pio\build\d1_mini\libf7d\libEspfc.a
Compiling .pio\build\d1_mini\FrameworkArduino\Crypto.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\Esp-frag.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\Esp-version.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\Esp.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\FS.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\FSnoop.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\FunctionalInterrupt.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\HardwareSerial.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\IPAddress.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\LwipDhcpServer-NonOS.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\LwipDhcpServer.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\LwipIntf.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\LwipIntfCB.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\MD5Builder.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\Print.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\Schedule.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\StackThunk.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\Stream.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\StreamSend.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\Tone.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\TypeConversion.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\Updater.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\WMath.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\WString.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\abi.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\aes_unwrap.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\base64.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\cbuf.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\cont.S.o
Compiling .pio\build\d1_mini\FrameworkArduino\cont_util.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\core_esp8266_app_entry_noextra4k.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\core_esp8266_eboot_command.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\core_esp8266_features.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\core_esp8266_flash_quirks.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\core_esp8266_flash_utils.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\core_esp8266_i2s.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\core_esp8266_main.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\core_esp8266_non32xfer.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\core_esp8266_noniso.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\core_esp8266_phy.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\core_esp8266_postmortem.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\core_esp8266_si2c.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\core_esp8266_sigma_delta.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\core_esp8266_spi_utils.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\core_esp8266_timer.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\core_esp8266_vm.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\core_esp8266_waveform_phase.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\core_esp8266_waveform_pwm.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\core_esp8266_wiring.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\core_esp8266_wiring_analog.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\core_esp8266_wiring_digital.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\core_esp8266_wiring_pulse.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\core_esp8266_wiring_pwm.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\core_esp8266_wiring_shift.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\crc32.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\debug.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\exc-c-wrapper-handler.S.o
Compiling .pio\build\d1_mini\FrameworkArduino\exc-sethandler.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\flash_hal.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\gdb_hooks.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\heap.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\hwdt_app_entry.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\libb64\cdecode.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\libb64\cencode.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\libc_replacements.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\mmu_iram.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\reboot_uart_dwnld.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\spiffs\spiffs_cache.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\spiffs\spiffs_check.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\spiffs\spiffs_gc.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\spiffs\spiffs_hydrogen.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\spiffs\spiffs_nucleus.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\spiffs_api.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\sqrt32.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\stdlib_noniso.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\time.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\uart.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\umm_malloc\umm_info.c.o
Compiling .pio\build\d1_mini\FrameworkArduino\umm_malloc\umm_integrity.c.o
Compiling .pio\build\d1_mini\FrameworkArduino\umm_malloc\umm_local.c.o
Compiling .pio\build\d1_mini\FrameworkArduino\umm_malloc\umm_malloc.cpp.o
Compiling .pio\build\d1_mini\FrameworkArduino\umm_malloc\umm_poison.c.o
Archiving .pio\build\d1_mini\libFrameworkArduino.a
Linking .pio\build\d1_mini\firmware.elf
Retrieving maximum program size .pio\build\d1_mini\firmware.elf
Checking size .pio\build\d1_mini\firmware.elf
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [======    ]  61.2% (used 50100 bytes from 81920 bytes)
Flash: [====      ]  36.8% (used 384275 bytes from 1044464 bytes)
Building .pio\build\d1_mini\firmware.bin
Creating BIN file ".pio\build\d1_mini\firmware.bin" using "C:\Users\autoplantbali\.platformio\packages\framework-arduinoespressif8266\bootloaders\eboot\eboot.elf" and ".pio\build\d1_mini\firmware.elf"
Configuring upload protocol...
AVAILABLE: espota, esptool
CURRENT: upload_protocol = esptool
Looking for upload port...
Using manually specified: COM4
Uploading .pio\build\d1_mini\firmware.bin
esptool.py v3.0
Serial port COM4
Connecting....
Chip is ESP8266EX
Features: WiFi
Crystal is 26MHz
MAC: a8:48:fa:dc:e2:d4
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 460800
Changed.
Configuring flash size...
Compressed 388432 bytes to 277058...
Writing at 0x00000000... (5 %)
Writing at 0x00004000... (11 %)
Writing at 0x00008000... (17 %)
Writing at 0x0000c000... (23 %)
Writing at 0x00010000... (29 %)
Writing at 0x00014000... (35 %)
Writing at 0x00018000... (41 %)
Writing at 0x0001c000... (47 %)
Writing at 0x00020000... (52 %)
Writing at 0x00024000... (58 %)
Writing at 0x00028000... (64 %)
Writing at 0x0002c000... (70 %)
Writing at 0x00030000... (76 %)
Writing at 0x00034000... (82 %)
Writing at 0x00038000... (88 %)
Writing at 0x0003c000... (94 %)
Writing at 0x00040000... (100 %)
Wrote 388432 bytes (277058 compressed) at 0x00000000 in 6.6 seconds (effective 470.7 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...
--- Terminal on COM4 | 115200 8-N-1
--- Available filters and text transformations: colorize, debug, default, direct, esp8266_exception_decoder, hexlify, log2file, 
nocontrol, printable, send_on_enter, time
--- More details at https://bit.ly/pio-monitor-filters
--- Quit: Ctrl+C | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H
rl␀l�r␂$␒�n␌␌␌�␌l�␌b|��␂␇␒�r␒b�␌b␄�nn␂lnn␒b␌b␜p�$b␎lrlp�n␐␂␌␌�␌l␌�␂␌␌␌b␌n�n�␌�␄␌b��nn'l�␄l`␂�␒␒nn␌$`␂␎␂nr���n␌␌rr�`␂p�n0␂␌␌r�␜␜b ␄␂␌b␌n�n␌␄␌b��nn'␌␄l`␂�␒␒nn␌$`␂␎␂nr���n␌␌r␒l`␂␎r��n␌␌r␒l`␂�␂␌␌l$0�␌l`␂��n�`␂ I UART 0 0 1 115200 -1 -1 
 I UART 1 1 128 250000 -1 -1 
 I EEPROM loaded
 I I2C SETUP 1000 1
 I I2C DETECT MPU9250 0 
 I I2C DETECT MPU6050 1 
 I MOTOR CONF 5 0 480 1
 I MOTOR PIN 0 0
 I MOTOR PIN 1 14
 I MOTOR PIN 2 12
 I MOTOR PIN 3 15
 I GYRO INIT MPU6050 0 8000 2000 500
 I ACCEL INIT MPU6050 502 1990 1 
 I FUSION MADGWICK 50
 I RX PPM 13 1
 I GYRO BIAS -1.13 -1.51 0.86 


I also tried using the serial monitor on Arduino Ide to type status but there was no response back from the Wemos D1 mini serial

**Comment by AutoPlantBali** [comment]
![status](https://github.com/rtlopez/esp-fc/assets/100328812/7d26a952-58f5-4cbe-96c1-17a975a12be3)

this response using putty

**Comment by AutoPlantBali** [comment]
![stats](https://github.com/rtlopez/esp-fc/assets/100328812/59034234-17d0-4d36-9d87-a5ea2f114da8)

**stats** command

**Comment by rtlopez** [comment]
Hi,

I created fix for serial on esp8266, but still can't connect from configurator 10.9. 10.8 works for me, but I'm not sure if the system matters here, I'm using Linux. If you want to test it, solution is in PR #33 (branch `serial-fix`)

Cheers,

**Comment by AutoPlantBali** [comment]
hi rtlopez, thanks for fixing for connect betaflight configurator 10.8

i'am pull serial-fix, use windows 10, this same, configurator 10.9 not work but 10.8 works... esp8266 only gyro sensor mpu6050 with cpu_load average 85%

I don't know if it's still working normally after adding a motor and rx receiver with cpu_load above 85%

**Comment by AutoPlantBali** [comment]
![esp32_mpu9250](https://github.com/rtlopez/esp-fc/assets/100328812/aba2fb65-3f4a-4512-8661-c1ed5e92af00)

esp32 spi gyro MPU-9250 doesn't work, I've tried connecting to SPI0 or SPI1, if using I2C it works but the barometer doesn't work and load_cpu is up to 99% and sometimes it hangs on the uart communication

**Comment by rtlopez** [comment]
Hi 

```
git checkout master
git pull
```
And try again, I just merged bunch of updates :)

**Comment by AutoPlantBali** [comment]
result pull commit 2d713ef0fb35355ade33baf359c044538a3736c2

========== esp8266 use mpu6050 i2c =============
![esp8266_mpu6050](https://github.com/rtlopez/esp-fc/assets/100328812/a24e6657-a2d7-4b00-93da-10fc9c578ffc)

========== esp8266 use mpu9250 i2c =============
![esp8266_mpu9250](https://github.com/rtlopez/esp-fc/assets/100328812/70321226-538b-474b-9461-b37f18e19311)

========== esp32 use mpu6050 i2c ===============
![esp32_mpu6050](https://github.com/rtlopez/esp-fc/assets/100328812/64c54104-b3dd-45cc-baf2-8b5f39e9e84c)

========== esp32 use mpu9250 i2c ===============
![esp32_mpu9250_i2c](https://github.com/rtlopez/esp-fc/assets/100328812/3d41cdbf-3fdd-4aed-a6a8-ccc0fb61f597)

========== esp32 use mpu9250 spi0 ==============
![esp32_mpu9250_spi0](https://github.com/rtlopez/esp-fc/assets/100328812/1c96a79d-ca6b-404d-b945-9e75f51b4e17)


===> spi is faster than i2c and load_cpu is smaller
===> brushed motor only works on esp8266 and esp32 doesn't work
===> esp8266 and esp32 connect and disconnect several times in betaflight sometimes it makes the settings return to default settings
