### ISSUE TITLE
Progress

### ISSUE THREAD

**Issue by europer** [rtlopez/esp-fc#5]
Fantastic, did you build one (YouTube or photo) and have you developt more on this issue like esp32? Did see dshot but in the code dshot150-300 and 600-1200 missing?
Anyway interesting code 👍

**Comment by rtlopez** [comment]
@europer Thanks, 
I've built and flew one on esp8266, unfortunately I haven't made the video yet, but I will think about it. Esp32 development is in progress. Dshot 600 and 1200 implementation is not stable enough, especially on esp8266.
