### ISSUE TITLE
Not arm my quad

### ISSUE THREAD

**Issue by skimans** [rtlopez/esp-fc#62]
Hi
i have install last version of firmware for my ESP32 but when i connect battery not arm the quad.
I use MPU6050 and my radio is Flysky I6.

how i can solve ?

thanks
![IMG20230819120018](https://github.com/rtlopez/esp-fc/assets/78317991/420c0763-356a-47b0-8ac4-9e6402b5c08b)
![Immagine](https://github.com/rtlopez/esp-fc/assets/78317991/3525f49a-f533-456a-8ca2-165b69d057e2)
![Immagine1](https://github.com/rtlopez/esp-fc/assets/78317991/c29e4c21-f37b-4a72-aa5b-9974f58e0103)
![Immagine2](https://github.com/rtlopez/esp-fc/assets/78317991/7176dc48-1005-41dc-b4ca-1097a25c3fef)
![Immagine3](https://github.com/rtlopez/esp-fc/assets/78317991/dd618e9f-0641-41c2-a38e-ff6449fde8c7)

**Comment by rtlopez** [comment]
Hi @skimans, 

It seems that you gyro is very noisy and callibration not finishing. Ensure your model is not moving when you connecting it. Consider mounting it with using adhesive tape and solder with flex cables instead direct soldering. If it won't help, you should look for replacement.

**Comment by skimans** [comment]
Hi
I have solved.
Was a problem on my gyro/acc.
I have used GY87 but not work becouse i have used 3,3 volt.
Now i have used GY521...normal MPU6050 and now work fine

One question . It's posible have a version firmware for Inav ?

Thanks much.
And my complimentes for this your wonderful project.

Stefano


Il sab 19 ago 2023, 16:10 rtlopez ***@***.***> ha scritto:

**Comment by rtlopez** [comment]
What do you mean by 
> firmware version for Inav?

This firmware is neither Betaflight nor Inav. It is only partialy compatible to work with Betaflight-configurator. Not all features are available here.
