### ISSUE TITLE
Only Angle flight mode ?

### ISSUE THREAD

**Issue by skimans** [rtlopez/esp-fc#63]
Hi
i have saw that in the firmware is only available Angle mode that is very difficult to drive the quad.
It's posibile add also Acro mode or flight mode more slow and easy to drive the quad ?

thanks much

**Comment by rtlopez** [comment]
Hi,

Actually the `Angle` mode is easier to fly. In this mode quad automatically `self-level` to horizon if sticks are in center position. `Acro` is a default flight mode if no `Angle` mode is engaged. You can tune both modes to your preferences
1. For `Acro` mode options are in `pid tuning` -> `rate profile` tab: `center sensitivity/max rate/expo`
2. For `Angle` mode options are in `pid tuning` -> `pid profile settings` tab: `angle strength` and `angle limit`.
