### ISSUE TITLE
Change motor spinning direction

### ISSUE THREAD

**Issue by Lisanderl** [rtlopez/esp-fc#64]
Hello!
I've tried to use CLI ti change motor spinning direction from N to R (set output_0 M R 1000 1500 2000). But It has no effect.
I also try to play with limits like change 1000-2000 to 2000-1000 and have same result.

Maybe I do something in a wrong way ?

**Comment by rtlopez** [comment]
Hi @Lisanderl,

this function is intended to reversing servos, not motors. To change motor direction you have two options
1. use spare fc or 4way interface to programm ESC, this firmware doesn't support this function yet
2. swap two motor wires

**Comment by Lisanderl** [comment]
Oh, I see. Going to swap motor wires, thanks!
