### ISSUE TITLE
RP2040 not connect betaflight configurator 10.9.0 after set PID loop 2khz

### ISSUE THREAD

**Issue by AutoPlantBali** [rtlopez/esp-fc#67]
hi..
I tried rp2040 zero with mpu9250, set the PID loop frequency to 2khz after that it can't be connected to betaflight configurator 10.9.0, if set to 1khz it still runs

![rp2040_2khz](https://github.com/rtlopez/esp-fc/assets/100328812/7da0287a-3ff9-4987-84ae-5abf9239f5ef)

**Comment by bsvdoom** [comment]
i think 1khz is the max.

**Comment by AutoPlantBali** [comment]
I also think so, maybe the 2khz option needs to be removed because after it's set it can't be fixed by flashing again, you have to clean the eeprom on the rp2040 which isn't as easy as on the esp8266 and esp32

**Comment by rtlopez** [comment]
Hi @AutoPlantBali Thanks for the report, I'm mostly focused on esp32 stabilization right now and don't test the rp2040 much. But will look at it soon.

**Comment by AutoPlantBali** [comment]
Okay @rtlopez, thank you very much..
