### ISSUE TITLE
ESP32-C3 support?

### ISSUE THREAD

**Issue by bsvdoom** [rtlopez/esp-fc#69]
I started to make a new target for the [ESP32-C3](https://docs.ai-thinker.com/_media/esp32/docs/esp-c3-32s-kit-v1.0_specification.pdf).

Now betaflight can connect and it looks like it works, but some lines produce errors and needs to be rewritten as I saw, but I lack the knowledge to do so.. (now they are just commented out to see if it works):

Can you help me fix these please, do you have an idea how to do this, should I make a pullrq into a new branch?
Thanks!

**Comment by AutoPlantBali** [comment]
i'm not sure it will run well with limited number of IO pins and only have 1 core

**Comment by bsvdoom** [comment]
the esp8266 has less pins and 1 core as well, and it runs on that too..

**Comment by bsvdoom** [comment]
Some more work, and all options seems to work in betaflight, but:
-Gyro slowly rotates to the right at 5dec/sec
-Motor outputs does not seem to work correctly
-Cannot set the PID cycle above 0.5kHz
-If I enable the baro, it freezes on the next boot after the message "I I2C DETECT MPU6050"

**Comment by rtlopez** [comment]
@bsvdoom Thanks, that looks pretty decent. If you could do a PR, I'd put some comments. Nevertheless, the fact is that in the case of the C3 we have fewer IO pins available than in the ESP8266 IIRC.

**Comment by bsvdoom** [comment]
@rtlopez As far as I know ESP8266 has 17 (ESP12-F has 9), and ESP32-C3 has 21 available IO pins.
I made the PR #70, so I close this issue now, thanks!
