### ISSUE TITLE
This ESP32 can work fine ??

### ISSUE THREAD

**Issue by skimans** [rtlopez/esp-fc#77]
Hi friends
this ESP Wroom 32 can work fine ?
the pin are differents...

![IMG20230902222412](https://github.com/rtlopez/esp-fc/assets/78317991/3da53fc3-7d74-4617-8516-e37ec46b4288)

**Comment by rtlopez** [comment]
Hi @skimans Yes, I belive, it seems to be esp32 devkit v1.
