### ISSUE TITLE
MPU6500 not work

### ISSUE THREAD

**Issue by skimans** [rtlopez/esp-fc#80]
hi friends
i have install MPU6500 using this pinout but not work:

![image](https://github.com/rtlopez/esp-fc/assets/78317991/8d6bed7a-11be-46a0-be02-c76b542adb74)

i have connected with 3.3V (the same in Inav where work fine).

![IMG20230904222355](https://github.com/rtlopez/esp-fc/assets/78317991/6daa0a91-8abb-45d7-8b4a-c3e625b43cad)

![image](https://github.com/rtlopez/esp-fc/assets/78317991/9d80c26b-06c2-48f7-9ccc-8a5499908a95)

**Comment by AutoPlantBali** [comment]
hi @skimans..
MOSI pin (IO23) on ESP32 connect to ADO pin on mpu6500

**Comment by skimans** [comment]
> hi @skimans.. MOSI pin (IO23) on ESP32 connect to ADO pin on mpu6500

![IMG20230904231119](https://github.com/rtlopez/esp-fc/assets/78317991/2340b31b-cc46-4155-bf8c-55c6f66f787c)

hi @AutoPlantBali 
i have connected now IO23 to ADO but not work.

**Comment by AutoPlantBali** [comment]
oopss..sorry @skimans 
ESP32 PIN  --------> MPU6500 PIN
IO18           --------> SCL
IO19           --------> ADO
IO23           --------> SDA
IO5             --------> NCS

**Comment by skimans** [comment]
@AutoPlantBali now work. Thanks much!!
