### ISSUE TITLE
Error to flash firmware

### ISSUE THREAD

**Issue by skimans** [rtlopez/esp-fc#82]
hi
after using Arduino for check I2c address i have tried to reinstall firmware Alpha5, but when i flash i have this error message:

![image](https://github.com/rtlopez/esp-fc/assets/78317991/d3f3310f-cb0a-410e-bb24-03fabe980604)

how i can solve it ?

**Comment by rtlopez** [comment]
Hi @skimans 

1. this screenshot is too small, it would be good if you provide fragment with upload configuration
2. what have you done so far to resolve this issue?
3. have you tried change cable or reset flash 
4. have you read first google link https://www.google.com/search?q=md5+of+file+does+not+match+data+in+flash
5. do you have anything connected to gpio strapping pins 2 or 12?

**Comment by skimans** [comment]
Hi @rtlopez  thanks for your patience.
I have read in the web also your link but i dont have found solution.
I have also changed the cable.
I think that i have bricked my ESP32 using Arduino.

Muchas gracias rtlopez. Creo que termina aca mi esperencia con ESP32.
Desculpame si te o molestado mucho a preguntarte muchas informaciones.
Sigue adelante asi con tu proyecto!
Felicidades!

**Comment by rtlopez** [comment]
Hi @skimans No te rindas amigo y sigue adelante. Creo que lo lograrás :) Créeme, aprender también requiere paciencia :)

**Comment by AutoPlantBali** [comment]
hi.. @skimans , follow this step:

=> connect esp32 and set bautrate 115200
![set_bautrate](https://github.com/rtlopez/esp-fc/assets/100328812/e7f4763d-1bb7-4c9e-8681-e7730e13d35e)

=> set flash address and click program
![flash](https://github.com/rtlopez/esp-fc/assets/100328812/4e5b62bd-7c37-4413-b41d-b713c01248e2)

=> finish
![finish](https://github.com/rtlopez/esp-fc/assets/100328812/8bbcfd20-8cc9-49df-88ef-c6ac44685e60)

==> all file flash
[espfc.zip](https://github.com/rtlopez/esp-fc/files/12558669/espfc.zip)

**Comment by skimans** [comment]
@AutoPlantBali thanks much! i have solved.
ESP32 recovered.

**Comment by AutoPlantBali** [comment]
@skimans.... u're welcome... please close all issues that have been solved so that it's easier to handle
