### ISSUE TITLE
ESC not working.

### ISSUE THREAD

**Issue by ArshaanTech** [rtlopez/esp-fc#94]
Hi I am using "30A Brushless Motor Speed Controller RC Bec Esc for Quadcopter Plane Helicopter" ESC
![image](https://github.com/rtlopez/esp-fc/assets/85013497/0138f3b5-cf61-40c8-bdfc-d1ca71e2bb21)
and for some reason the motors are not spinning... I tried all the available protocols but no luck :( What could be the reason for this problem and how do I solve it.

**Comment by khunglong207** [comment]
@rtlopez help pls

**Comment by Mathew3000** [comment]
did you do a PWM calibration for your ESC? and can you confirm the signal is on the pin?

**Comment by ArshaanTech** [comment]
just set the pwm frequency to 60 hertz and common the ground it will work!
