### ISSUE TITLE
Lolin s2 mini

### ISSUE THREAD

**Issue by Boak29** [rtlopez/esp-fc#95]
this is support lolin s2 mini?

**Comment by rtlopez** [comment]
S2 is not supported yet.

**Comment by Boak29** [comment]
Thanks for answer

**Comment by Boak29** [comment]
![IMG_20231027_055626_119.jpg](https://github.com/rtlopez/esp-fc/assets/93535477/34952915-b548-4f44-8238-817643951a74)

Btw i have alrady with d1 mini. Tq
